#!/bin/sh

threshold=10

is_battery_ok() {
    cap=$(cat /sys/class/power_supply/BAT0/capacity)
    stat=$(cat /sys/class/power_supply/BAT0/status)
    [ "$cap" -ge "$threshold" ] || [ "$stat" == "Charging" ]
}

hibernate() {
    i3-nagbar -m "Battery level less then "$threshold"%, turning off in 30sec!" &
    sleep 30
    if ! is_battery_ok
    then
        sudo systemctl poweroff
    fi
}

if ! is_battery_ok
then
    hibernate
fi

