#!/bin/sh

threshold=10

is_battery_ok() {
    # sometimes when kernel updates the battery switches places, so we need
    # to monitor both entries
    cap=$(cat /sys/class/power_supply/BAT"${1}"/capacity)
    stat=$(cat /sys/class/power_supply/BAT"${1}"/status)
    [ "$cap" -ge "$threshold" ] || [ "$stat" == "Charging" ]
}

poweroff() {
    i3-nagbar -m "Battery level less then "$threshold"%, turning off in 30sec!" &
    sleep 30
    if ! is_battery_ok 0 || ! is_battery_ok 1
    then
        sudo systemctl poweroff
    fi
}

if ! is_battery_ok 0 || ! is_battery_ok 1
then
    poweroff
fi

