# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000
HISTIGNORE='ls:ll:bg:fg:history'
HISTTIMEFORMAT='%F %T '

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Reset
Color_Off='\e[0m'

# Regular Colors
Black='\e[0;30m'
Red='\e[0;31m'
Green='\e[0;32m'
Yellow='\e[0;33m'
Blue='\e[1;34m'
Purple='\e[0;35m'
Cyan='\e[0;36m'
White='\e[0;37m'

function __prompt_command() {
    EXIT="$?"
    PS1=""

    # command history number in green if ok, red - if not
    if [ $EXIT -eq 0 ]; then PS1+="\[$Green\][\!]\[$Color_Off\] "; else PS1+="\[$Red\][\!]\[$Color_Off\] "; fi

    # basic information (user@host:path)
    PS1+="\[$Green\]\u\[$Color_Off\]@\[$Green\]\h\[$Color_Off\]:\[$Blue\]\w\[$Color_Off\] "

    # add git display to prompt
    local git_status="$(git status -unormal 2>&1)"
    if ! [[ "$git_status" =~ not\ a\ git\ repo ]]; then
        # repository in unmodified state
        if [[ "$git_status" =~ nothing\ to\ commit ]]; then
            local Color_On=$Green
        # modified files already present in repository
        elif [[ "$git_status" =~ no\ changes\ added\ to\ commit ]]; then
            local Color_On=$Purple
        # new files in repository
        else
            local Color_On=$Red
        fi
        # brach info
        if [[ "$git_status" =~ On\ branch\ ([^[:space:]]+) ]]; then
            branch=${BASH_REMATCH[1]}
        else
            # Detached HEAD. (branch=HEAD is a faster alternative.)
            branch="`git describe --all --contains --abbrev=4 HEAD 2> /dev/null || echo HEAD`"
        fi
        PS1+="\[$Color_On\][$branch]\[\e[0m\] "
    fi

    if [[ "$VIRTUAL_ENV" != "" ]]; then
        PS1+="\[\e[1;30m\]($(basename $VIRTUAL_ENV))\[\e[0m\] "
    fi

    # prompt $ or # for root
    PS1+='\n\$ '
}

PROMPT_COMMAND=__prompt_command

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    # -N gets rid of nasty apostrophe in file listing
    alias ls='ls --color=auto -N'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# less customization
export LESS='-M -I -# 4'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias myip='ip -br -c a'
alias kc='kubectl'

# setup kc alias completion
# https://github.com/cykerway/complete-alias
source ~/.bash_completion.d/complete_alias
complete -F _complete_alias kc

alias dates='TZ="Australia/Brisbane" date; TZ="Asia/Shanghai" date; TZ="Europe/Warsaw" date; TZ=UTC date; TZ="America/New_York" date; TZ="America/Phoenix" date; TZ="America/Los_Angeles" date'
function start_ssh_agent() {



function start_ssh_agent() {
    SSH_ENV="$HOME/.ssh/environment"
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
}

function vscode() {
    if [[ "$#" == "0" ]]; then
        /usr/bin/code
    else
        /usr/bin/code /home/maszulik/workspace/"$1".code-workspace
    fi
}

function ec2list() {
    aws ec2 describe-instances \
        --filters "Name=instance-state-name,Values=running" "Name=tag:Name,Values=$1" \
        --query 'Reservations[].Instances[].[Tags[?Key==`Name`] | [0].Value,PublicDnsName] | sort_by(@, &[0])' \
        --output text
}

function timer() {
    at now + $1 minute <<< 'DISPLAY=:0 i3-nagbar -t warning -m "Have a short break!"'
}

# go settings
function __update_path() {
    new="$1"
    old="$2"
    if [[ $PATH == *"$old"* ]]; then
        export PATH="${PATH/$old/$new}"
    elif [[ $PATH == *"$new"* ]]; then
        : # do nothing
    else
        export PATH=$new:$PATH
    fi
}

function goorigin() {
    __update_path $HOME/workspace/origin/bin $HOME/workspace/k8s/bin
    gvm use go1.15
    export GOPATH=$HOME/workspace/origin
    export GOFLAGS=-mod=vendor
    cd $GOPATH/src/github.com/openshift
}

function gok8s() {
    __update_path $HOME/workspace/k8s/bin $HOME/workspace/origin/bin
    gvm use go1.15
    export GOPATH=$HOME/workspace/k8s
    export GOFLAGS=-mod=vendor
    cd $GOPATH/src/k8s.io/kubernetes
}

# bash variables
export EDITOR=vim
export PATH=$HOME/usr/bin:$HOME/.krew/bin:$HOME/.local/bin/:$PATH

[[ -s "/home/maszulik/.gvm/scripts/gvm" ]] && source "/home/maszulik/.gvm/scripts/gvm"

